version: '3.8'

services:
  dockports_container:
    container_name: dockports-container
    image: dockports
    environment:
      LANG: C.UTF-8
      GPG_KEY: A035C8C19219BA821ECEA86B64E628F8D684696D
      PYTHON_VERSION: 3.11.13
      PYTHON_SHA256: 8fb5f9fbc7609fa822cb31549884575db7fd9657cbffb89510b5d7975963a83a
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
      DOCKPORTS_PORT: '7577'
    volumes:
      - /home/DockPorts/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    entrypoint:
      - python
      - app.py
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:${DOCKPORTS_PORT}/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
