version: '3.8'

services:
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:0.4
    restart: unless-stopped
    environment:
      PDS_BLOB_UPLOAD_LIMIT: '52428800'
      PDS_JWT_SECRET: 3e434f02cea26b8acae4e1d97fb5ad5c
      HTTP_PROXY: http://192.168.0.132:7890
      PDS_REPORT_SERVICE_URL: https://mod.bsky.app
      GLOBAL_AGENT_HTTP_PROXY: http://192.168.0.132:7890
      GLOBAL_AGENT_NO_PROXY: localhost,127.0.0.1,*.corain.fun
      PDS_ADMIN_PASSWORD: f0ccc074428d671ba9e99165ef1a4a00
      PDS_DID_PLC_URL: https://plc.directory
      HTTPS_PROXY: http://192.168.0.132:7890
      PDS_HTTP_CLIENT_TIMEOUT: '30000'
      PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: 71ea55f251923fe8cc136fc711febe486687279805d66f1337d6f98cd215632d
      PDS_HOST: 0.0.0.0
      LOG_ENABLED: 'true'
      GLOBAL_AGENT_HTTPS_PROXY: http://192.168.0.132:7890
      PDS_DATA_DIRECTORY: /pds
      PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
      PDS_BSKY_APP_VIEW_URL: https://api.bsky.app
      PDS_HOSTNAME: cherry.corain.fun:16443
      PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
      PDS_CRAWLERS: https://bsky.network
      NODE_VERSION: 20.11.1
      YARN_VERSION: 1.22.19
      PDS_PORT: '3000'
      NODE_ENV: production
      UV_USE_IO_URING: '0'
    volumes:
      - /pds:/pds
    network_mode: host
    entrypoint:
      - dumb-init
      - --
    command:
      - node
      - --enable-source-maps
      - index.js
