version: '3.8'

services:
  docker2compose:
    image: jackie264/docker2compose:latest
    # Docker Hub：jackie264/docker2compose:latest
    # GitHub 容器注册表 ： ghcr.io/coracoo/docker2compose:latest
    # 国内阿里云镜像仓库: crpi-xg6dfmt5h2etc7hg.cn-hangzhou.personal.cr.aliyuncs.com/cherry4nas/docker2compose:latest
    container_name: docker2compose
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config
      - ./compose:/app/compose
    environment:
      - TZ=Asia/Shanghai
      - CRON=0 2 * * *  # 每天凌晨2点运行
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker2compose.rule=Host(`docker2compose.local`)"
      - "traefik.http.services.docker2compose.loadbalancer.server.port=5000"

  # 可选：添加反向代理
  nginx:
    image: nginx:alpine
    container_name: docker2compose-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - docker2compose
    restart: unless-stopped
    profiles:
      - with-proxy