version: '3'
services:
  upsnap2_upsnap_1:
    container_name: upsnap2-upsnap-1
    image: seriousm4x/upsnap:4
    environment:
      TZ: Asia/Shanghai
    network_mode: host
    healthcheck:
      test:
      - CMD-SHELL
      - curl -fs "http://localhost:8090/api/health" || exit 1
      interval: 10000000000
